name: brush Step count

on:
  workflow_dispatch:
  schedule:
   - cron: 18 0,5,10,14 * * *

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
     
      - name: Up
        run: |
          pip install requests
          pmode='${{ secrets.PMODE }}'
          pkey='${{ secrets.PKEY }}'
          user='${{ secrets.USER }}'
          pwd='${{ secrets.PWD }}'
          step='${{ secrets.STEP }}'
          python3 main.py ${pmode} ${pkey} ${user} ${pwd} ${step}
          
      - name: Update Time
        run: |
          time=$(TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S')
          sed -i "s/^最后一次运行时间:.*/最后一次运行时间: $time （北京时间） /g" README.md
          
      - name: Git push assets to Github
        run: |
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git branch -m master
          git add --all
          git commit -m "Updated at $(TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S')（北京时间）"
          git push -u origin -f
